### ISSUE TITLE
You have to fix issue with is_connected function

### ISSUE THREAD

**Issue by AntonSivov** [amperka/gprs-shield#6]
Hello in your code - in is_connected function  you check CONNECTED but AT returns CONNECT
 //+CIPSTATUS: 1,0,"TCP","216.52.233.120","80","CONNECTED"

**Comment by nkrkv** [comment]
@Igor89 Take a look, please

**Comment by nomad605dis** [comment]
Hello!
We are currently updating the library. There will be all fixed.
