### ISSUE TITLE
Serial1 was not declared in this scope

### ISSUE THREAD

**Issue by jenokizm** [amperka/gprs-shield#9]
Ваши примеры не работают. Ошибка

> GPRSSendSMSamperka:10:11: error: 'Serial1' was not declared in this scope
> GPRS gprs(Serial1);
> Serial1.begin(9600);
> it status 1
> 'Serial1' was not declared in this scope

**Comment by nomad605dis** [comment]
Добрый день! Подскажите, а какая у вас управляющая плата Arduino?

вт, 25 дек. 2018 г. в 18:18, jenokizm <notifications@github.com>:

**Comment by jenokizm** [comment]
Добрый, UNO обычная у вас покупал. Хотя валяется еще где то у меня искра могу достать.

**Comment by jenokizm** [comment]
Хотя тут походу дело не в плате, а в вашем коде. Ошибка на этапе компиляции выскакивает. Даже логически по коду понятно что объект Serial1 нигде не определен и непонятно какого он класса. Я попробовал его определить так:
`SoftwareSerial Serial1(2, 3);`
код скомпилился и запустился, но смс не отправляется. в цикле выводятся сообщения

> GPRS Init error

**Comment by nomad605dis** [comment]
Добрый день!

На всех платах Iskra и Arduino присутствует хотя бы один аппаратный UART —
HardwareSerial <https://www.arduino.cc/en/Reference/Serial>. Если же по
каким то причинам он занят другим устройством, можно воспользоваться
программным UART — SoftwareSerial.
<https://www.arduino.cc/en/Reference/SoftwareSerial>

Так вот пример который вы используете рассчитан на аппаратный UART Serial1,
которого нет в платформе Arduino Uno.

С платой Arduino Uno, можно воспользоваться программный UART. Прочитайте
документацию на GPRS Shield, там мы всё расписали.

http://wiki.amperka.ru/продукты:gprs-shield

вт, 25 дек. 2018 г. в 19:33, jenokizm <notifications@github.com>:

**Comment by jenokizm** [comment]
Понял, спасибо Игорь!
1. Подскажи где у вас можно купить джамперы такие как мелкие как в уроках по шилду? А то сейчас замыкаю RX и TX с соседними пинами проводными, а они много места занимают слишком...
2. Всегда задумывался при соединении с шилдом
`Serial1.begin(9600);`
вы выставляете 9600. Почему именно 9600 и не больше не меньше? На других сайтах в том числе русских видел выставляют 19200 а кто то наоборот меньше 2400. В своей статье вы этого не объясняете.
